services:
  web:
    image: nirnay2001/gpt6-portfolio-page:latest
    volumes:
      - mydata:/mydata
    ports:
      - "80:80"
    networks:
      - app-net1
    environment:
      - APP_VERSION=1.0.0
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - REDIS_URL=redis://cache:6379

volumes:
  mydata:
    name: mydata

networks:
  app-net1:
    name: app-net1
    driver: bridge