apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio

spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: ecr-secret      
      containers:
        - name: portfolio-container
          image: 474717635696.dkr.ecr.us-east-1.amazonaws.com/portfolio/app01:$IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "129Mi"
              cpu: "250m"