name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions

      - name: Test SSH key
        run: |
          ssh-keygen -y -f ~/.ssh/github_actions > /dev/null

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy website to EC2
        run: |
          rsync -avz --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            -e "ssh -i ~/.ssh/github_actions" \
            ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/website/

      - name: Deploy with docker
        run : |
          ssh -i ~/.ssh/github_actions ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            git clone https://github.com/Nirnay2001/GPT6-Portfolio-page.git
            cd GPT6-Portfolio-page
            docker build -t gpt6-portfolio .
            docker stop gpt6-portfolio || true
            docker rm gpt6-portfolio || true
            docker run -d -p 80:80 --name portfolio -p 80:80 gpt6-portfolio
          EOF
         
        
